### ISSUE TITLE
Error when using different themes.

### ISSUE THREAD

**Issue by aminecmi** [mr-pennyworth/alfred-gif#3]
Hello,

I can't figure out why, but using the "Alfred Model Dark" theme, I get the error below.

Using other themes like the "Alfred maxOS dark", or default "Alfred" theme the gif overlay is too high, and below the Alfred  bar, see the screen capture.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/510304/103228178-6fed1b80-4930-11eb-8b8a-63426c134543.png">

```
[17:12:10.647] GIF Search[Script Filter] Queuing argument 'g'
[17:12:10.721] GIF Search[Script Filter] Script with argv 'g' finished
[17:12:10.723] GIF Search[Script Filter] {"items": [
  {"title": "Search Tenor for \"g\"",
   "subtitle": "↩: search",
   "arg": "g"}]}
[17:12:10.735] GIF Search[Script Filter] Queuing argument 'gi'
[17:12:10.806] GIF Search[Script Filter] Script with argv 'gi' finished
[17:12:10.808] GIF Search[Script Filter] {"items": [
  {"title": "Search Tenor for \"gi\"",
   "subtitle": "↩: search",
   "arg": "gi"}]}
[17:12:10.849] GIF Search[Script Filter] Queuing argument 'gif'
[17:12:10.924] GIF Search[Script Filter] Script with argv 'gif' finished
[17:12:10.926] GIF Search[Script Filter] {"items": [
  {"title": "Search Tenor for \"gif\"",
   "subtitle": "↩: search",
   "arg": "gif"}]}
[17:12:11.266] GIF Search[Script Filter] Processing complete
[17:12:11.271] GIF Search[Script Filter] Passing output 'gif' to Run Script
[17:12:11.272] GIF Search[Script Filter] Passing output 'gif' to Run Script
[17:12:11.344] GIF Search[Run Script] Processing complete
[17:12:11.348] GIF Search[Run Script] Passing output '{"items": [
  {"title": "Searching for \"gif\"...",
   "subtitle": "Loading...",
   "arg": "gif",
   "valid": false}]}
' to Arg and Vars
[17:12:11.349] GIF Search[Arg and Vars] Processing complete
[17:12:11.350] GIF Search[Arg and Vars] Passing output '' to Call External Trigger
[17:12:11.350] GIF Search[External] Processing complete
[17:12:11.351] GIF Search[External] Passing output '' to Run Script
[17:12:11.409] GIF Search[Run Script] Processing complete
[17:12:11.417] GIF Search[Run Script] Passing output 'gif' to Script Filter
[17:12:11.439] GIF Search[Script Filter] Queuing argument 'gif'
[17:12:11.510] GIF Search[Script Filter] Script with argv 'gif' finished
[17:12:11.517] GIF Search[Script Filter] {"items": [
  {"title": "Searching for \"gif\"...",
   "subtitle": "Loading...",
   "arg": "gif",
   "valid": false}]}
[17:12:11.528] ERROR: GIF Search[Run Script] Traceback (most recent call last):
  File "./AlfredGifBrowser.app/Contents/Resources/scripts/alfred-gif-browser", line 47, in <module>
    with open(cssfilepath, 'w') as tmpfile: tmpfile.write(alfred.theme_css())
  File "/Users/aminecmi/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7688C4D2-C031-49BC-8A1B-4E8DF1CA8041/AlfredGifBrowser.app/Contents/Resources/scripts/alfred.py", line 53, in theme_css
    for varname, val in theme().items()
  File "/Users/aminecmi/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7688C4D2-C031-49BC-8A1B-4E8DF1CA8041/AlfredGifBrowser.app/Contents/Resources/scripts/alfred.py", line 18, in cached_func
    cache[args] = func(*args)
  File "/Users/aminecmi/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.7688C4D2-C031-49BC-8A1B-4E8DF1CA8041/AlfredGifBrowser.app/Contents/Resources/scripts/alfred.py", line 71, in theme
    theme_path = '%s/%s' % (DEFAULT_THEMES_DIR, bundled_theme_filename[theme_id])
KeyError: 'theme.bundled.moderndark'
[17:12:11.541] GIF Search[Run Script] Processing complete
[17:12:11.542] GIF Search[Run Script] Passing output '' to Arg and Vars
[17:12:11.543] GIF Search[Arg and Vars] Processing complete
[17:12:11.543] GIF Search[Arg and Vars] Passing output '' to Call External Trigger
[17:12:11.544] GIF Search[External] Processing complete
[17:12:11.545] GIF Search[External] Passing output '' to Run Script
[17:12:11.546] GIF Search[Run Script] Processing complete
[17:12:11.547] GIF Search[Run Script] Passing output 'gif' to Script Filter
[17:12:11.560] GIF Search[Script Filter] Queuing argument 'gif'
[17:12:11.637] GIF Search[Script Filter] Script with argv 'gif' finished
[17:12:11.648] GIF Search[Script Filter] {"items": [
  {"title": "Search Tenor for \"gif\"",
   "subtitle": "↩: search",
   "arg": "gif"}]}
   ```

**Comment by aminecmi** [comment]
Duplicate of #2.
